<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2015sp2

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://bio.tools" xmlns:agt="http://www.altova.com/Mapforce/agt" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="ns0 agt xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var2_create_shortDescription">
		<xsl:param name="var1_current"/>
		<shortDescription>
			<xsl:value-of select="string($var1_current)"/>
		</shortDescription>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var4_create_biotoolsID">
		<xsl:param name="var3_current"/>
		<biotoolsID>
			<xsl:value-of select="string($var3_current)"/>
		</biotoolsID>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var6_create_biotoolsCURIE">
		<xsl:param name="var5_current"/>
		<biotoolsCURIE>
			<xsl:value-of select="string($var5_current)"/>
		</biotoolsCURIE>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var8_create_listitem">
		<xsl:param name="var7_current"/>
		<list-item>
			<xsl:value-of select="string($var7_current)"/>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var10_create_type">
		<xsl:param name="var9_current"/>
		<type>
			<xsl:value-of select="string($var9_current)"/>
		</type>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var12_create_version">
		<xsl:param name="var11_current"/>
		<version>
			<xsl:value-of select="string($var11_current)"/>
		</version>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var14_create_listitem">
		<xsl:param name="var13_current"/>
		<list-item>
			<value>
				<xsl:value-of select="string($var13_current/ns0:value)"/>
			</value>
			<xsl:for-each select="$var13_current/ns0:type">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var10_create_type">
					<xsl:with-param name="var9_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var13_current/ns0:version">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var12_create_version">
					<xsl:with-param name="var11_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var16_create_uri">
		<xsl:param name="var15_current"/>
		<uri>
			<xsl:value-of select="string($var15_current)"/>
		</uri>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var18_create_term">
		<xsl:param name="var17_current"/>
		<term>
			<xsl:value-of select="string($var17_current)"/>
		</term>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var20_create_listitem">
		<xsl:param name="var19_current"/>
		<list-item>
			<xsl:for-each select="$var19_current/ns0:uri">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var16_create_uri">
					<xsl:with-param name="var15_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var19_current/ns0:term">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var18_create_term">
					<xsl:with-param name="var17_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var22_create_uri">
		<xsl:param name="var21_current"/>
		<uri>
			<xsl:value-of select="string($var21_current)"/>
		</uri>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var24_create_term">
		<xsl:param name="var23_current"/>
		<term>
			<xsl:value-of select="string($var23_current)"/>
		</term>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var26_create_uri">
		<xsl:param name="var25_current"/>
		<uri>
			<xsl:value-of select="string($var25_current)"/>
		</uri>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var28_create_term">
		<xsl:param name="var27_current"/>
		<term>
			<xsl:value-of select="string($var27_current)"/>
		</term>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var30_create_listitem">
		<xsl:param name="var29_current"/>
		<list-item>
			<xsl:for-each select="$var29_current/ns0:uri">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var26_create_uri">
					<xsl:with-param name="var25_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var29_current/ns0:term">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var28_create_term">
					<xsl:with-param name="var27_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var32_create_listitem">
		<xsl:param name="var31_current"/>
		<list-item>
			<data>
				<xsl:for-each select="$var31_current/ns0:data/ns0:uri">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var22_create_uri">
						<xsl:with-param name="var21_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
				<xsl:for-each select="$var31_current/ns0:data/ns0:term">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var24_create_term">
						<xsl:with-param name="var23_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</data>
			<format>
				<xsl:for-each select="$var31_current/ns0:format">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var30_create_listitem">
						<xsl:with-param name="var29_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</format>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var34_create_uri">
		<xsl:param name="var33_current"/>
		<uri>
			<xsl:value-of select="string($var33_current)"/>
		</uri>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var36_create_term">
		<xsl:param name="var35_current"/>
		<term>
			<xsl:value-of select="string($var35_current)"/>
		</term>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var38_create_uri">
		<xsl:param name="var37_current"/>
		<uri>
			<xsl:value-of select="string($var37_current)"/>
		</uri>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var40_create_term">
		<xsl:param name="var39_current"/>
		<term>
			<xsl:value-of select="string($var39_current)"/>
		</term>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var42_create_listitem">
		<xsl:param name="var41_current"/>
		<list-item>
			<xsl:for-each select="$var41_current/ns0:uri">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var38_create_uri">
					<xsl:with-param name="var37_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var41_current/ns0:term">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var40_create_term">
					<xsl:with-param name="var39_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var44_create_listitem">
		<xsl:param name="var43_current"/>
		<list-item>
			<data>
				<xsl:for-each select="$var43_current/ns0:data/ns0:uri">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var34_create_uri">
						<xsl:with-param name="var33_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
				<xsl:for-each select="$var43_current/ns0:data/ns0:term">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var36_create_term">
						<xsl:with-param name="var35_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</data>
			<format>
				<xsl:for-each select="$var43_current/ns0:format">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var42_create_listitem">
						<xsl:with-param name="var41_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</format>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var46_create_comment">
		<xsl:param name="var45_current"/>
		<comment>
			<xsl:value-of select="string($var45_current)"/>
		</comment>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var48_create_cmd">
		<xsl:param name="var47_current"/>
		<cmd>
			<xsl:value-of select="string($var47_current)"/>
		</cmd>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var50_create_listitem">
		<xsl:param name="var49_current"/>
		<list-item>
			<operation>
				<xsl:for-each select="$var49_current/ns0:operation">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var20_create_listitem">
						<xsl:with-param name="var19_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</operation>
			<input>
				<xsl:for-each select="$var49_current/ns0:input">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var32_create_listitem">
						<xsl:with-param name="var31_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</input>
			<output>
				<xsl:for-each select="$var49_current/ns0:output">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var44_create_listitem">
						<xsl:with-param name="var43_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</output>
			<xsl:for-each select="$var49_current/ns0:comment">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var46_create_comment">
					<xsl:with-param name="var45_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var49_current/ns0:cmd">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var48_create_cmd">
					<xsl:with-param name="var47_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var52_create_listitem">
		<xsl:param name="var51_current"/>
		<list-item>
			<xsl:value-of select="string($var51_current)"/>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var54_resultof_map">
		<xsl:param name="var53_current"/>
		<xsl:for-each select="$var53_current/ns0:toolType">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var52_create_listitem">
				<xsl:with-param name="var51_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var56_create_uri">
		<xsl:param name="var55_current"/>
		<uri>
			<xsl:value-of select="string($var55_current)"/>
		</uri>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var58_create_term">
		<xsl:param name="var57_current"/>
		<term>
			<xsl:value-of select="string($var57_current)"/>
		</term>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var60_create_listitem">
		<xsl:param name="var59_current"/>
		<list-item>
			<xsl:for-each select="$var59_current/ns0:uri">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var56_create_uri">
					<xsl:with-param name="var55_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var59_current/ns0:term">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var58_create_term">
					<xsl:with-param name="var57_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var62_resultof_map">
		<xsl:param name="var61_current"/>
		<xsl:for-each select="$var61_current/ns0:topic">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var60_create_listitem">
				<xsl:with-param name="var59_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var64_create_listitem">
		<xsl:param name="var63_current"/>
		<list-item>
			<xsl:value-of select="string($var63_current)"/>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var66_resultof_map">
		<xsl:param name="var65_current"/>
		<xsl:for-each select="$var65_current/ns0:goTermID">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var64_create_listitem">
				<xsl:with-param name="var63_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var68_create_listitem">
		<xsl:param name="var67_current"/>
		<list-item>
			<xsl:value-of select="string($var67_current)"/>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var70_resultof_map">
		<xsl:param name="var69_current"/>
		<xsl:for-each select="$var69_current/ns0:soTermID">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var68_create_listitem">
				<xsl:with-param name="var67_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var72_create_listitem">
		<xsl:param name="var71_current"/>
		<list-item>
			<xsl:value-of select="string($var71_current)"/>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var74_resultof_map">
		<xsl:param name="var73_current"/>
		<xsl:for-each select="$var73_current/ns0:taxID">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var72_create_listitem">
				<xsl:with-param name="var71_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var76_create_listitem">
		<xsl:param name="var75_current"/>
		<list-item>
			<xsl:value-of select="string($var75_current)"/>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var78_resultof_map">
		<xsl:param name="var77_current"/>
		<xsl:for-each select="$var77_current/ns0:operatingSystem">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var76_create_listitem">
				<xsl:with-param name="var75_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var80_create_listitem">
		<xsl:param name="var79_current"/>
		<list-item>
			<xsl:value-of select="string($var79_current)"/>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var82_resultof_map">
		<xsl:param name="var81_current"/>
		<xsl:for-each select="$var81_current/ns0:language">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var80_create_listitem">
				<xsl:with-param name="var79_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var84_create_license">
		<xsl:param name="var83_current"/>
		<license>
			<xsl:value-of select="string($var83_current)"/>
		</license>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var86_resultof_map">
		<xsl:param name="var85_current"/>
		<xsl:for-each select="$var85_current/ns0:license">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var84_create_license">
				<xsl:with-param name="var83_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var88_create_listitem">
		<xsl:param name="var87_current"/>
		<list-item>
			<xsl:value-of select="string($var87_current)"/>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var90_resultof_map">
		<xsl:param name="var89_current"/>
		<xsl:for-each select="$var89_current/ns0:collectionID">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var88_create_listitem">
				<xsl:with-param name="var87_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var92_create_maturity">
		<xsl:param name="var91_current"/>
		<maturity>
			<xsl:value-of select="string($var91_current)"/>
		</maturity>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var94_resultof_map">
		<xsl:param name="var93_current"/>
		<xsl:for-each select="$var93_current/ns0:maturity">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var92_create_maturity">
				<xsl:with-param name="var91_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var96_create_cost">
		<xsl:param name="var95_current"/>
		<cost>
			<xsl:value-of select="string($var95_current)"/>
		</cost>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var98_resultof_map">
		<xsl:param name="var97_current"/>
		<xsl:for-each select="$var97_current/ns0:cost">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var96_create_cost">
				<xsl:with-param name="var95_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var100_create_listitem">
		<xsl:param name="var99_current"/>
		<list-item>
			<xsl:value-of select="string($var99_current)"/>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var102_resultof_map">
		<xsl:param name="var101_current"/>
		<xsl:for-each select="$var101_current/ns0:accessibility">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var100_create_listitem">
				<xsl:with-param name="var99_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var104_create_listitem">
		<xsl:param name="var103_current"/>
		<list-item>
			<biotoolsId>
				<xsl:value-of select="string($var103_current/ns0:biotoolsID)"/>
			</biotoolsId>
			<type>
				<xsl:value-of select="string($var103_current/ns0:type)"/>
			</type>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var106_create_baseURL">
		<xsl:param name="var105_current"/>
		<baseURL>
			<xsl:value-of select="string($var105_current/ns0:baseURL)"/>
		</baseURL>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var108_create_uri">
		<xsl:param name="var107_current"/>
		<uri>
			<xsl:value-of select="string($var107_current)"/>
		</uri>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var110_create_term">
		<xsl:param name="var109_current"/>
		<term>
			<xsl:value-of select="string($var109_current)"/>
		</term>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var112_create_uri">
		<xsl:param name="var111_current"/>
		<uri>
			<xsl:value-of select="string($var111_current)"/>
		</uri>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var114_create_term">
		<xsl:param name="var113_current"/>
		<term>
			<xsl:value-of select="string($var113_current)"/>
		</term>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var116_create_listitem">
		<xsl:param name="var115_current"/>
		<list-item>
			<xsl:for-each select="$var115_current/ns0:uri">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var112_create_uri">
					<xsl:with-param name="var111_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var115_current/ns0:term">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var114_create_term">
					<xsl:with-param name="var113_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var118_create_listitem">
		<xsl:param name="var117_current"/>
		<list-item>
			<data>
				<xsl:for-each select="$var117_current/ns0:data/ns0:uri">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var108_create_uri">
						<xsl:with-param name="var107_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
				<xsl:for-each select="$var117_current/ns0:data/ns0:term">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var110_create_term">
						<xsl:with-param name="var109_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</data>
			<format>
				<xsl:for-each select="$var117_current/ns0:format">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var116_create_listitem">
						<xsl:with-param name="var115_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</format>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var120_create_summary">
		<xsl:param name="var119_current"/>
		<summary>
			<xsl:value-of select="string($var119_current)"/>
		</summary>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var122_create_uri">
		<xsl:param name="var121_current"/>
		<uri>
			<xsl:value-of select="string($var121_current)"/>
		</uri>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var124_create_term">
		<xsl:param name="var123_current"/>
		<term>
			<xsl:value-of select="string($var123_current)"/>
		</term>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var126_create_data">
		<xsl:param name="var125_current"/>
		<data>
			<xsl:for-each select="$var125_current/ns0:uri">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var122_create_uri">
					<xsl:with-param name="var121_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var125_current/ns0:term">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var124_create_term">
					<xsl:with-param name="var123_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</data>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var128_create_comment">
		<xsl:param name="var127_current"/>
		<comment>
			<xsl:value-of select="string($var127_current)"/>
		</comment>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var130_create_listitem">
		<xsl:param name="var129_current"/>
		<list-item>
			<urlTemplateFragment>
				<xsl:value-of select="string($var129_current/ns0:urlTemplateFragment)"/>
			</urlTemplateFragment>
			<xsl:for-each select="$var129_current/ns0:data">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var126_create_data">
					<xsl:with-param name="var125_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var129_current/ns0:comment">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var128_create_comment">
					<xsl:with-param name="var127_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var132_create_listitem">
		<xsl:param name="var131_current"/>
		<list-item>
			<httpMethod>
				<xsl:value-of select="string($var131_current/ns0:httpMethod)"/>
			</httpMethod>
			<urlTemplate>
				<xsl:value-of select="string($var131_current/ns0:urlTemplate)"/>
			</urlTemplate>
			<output>
				<xsl:for-each select="$var131_current/ns0:output">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var118_create_listitem">
						<xsl:with-param name="var117_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</output>
			<xsl:for-each select="$var131_current/ns0:summary">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var120_create_summary">
					<xsl:with-param name="var119_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<parameter>
				<xsl:for-each select="$var131_current/ns0:parameter">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var130_create_listitem">
						<xsl:with-param name="var129_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</parameter>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var134_resultof_map">
		<xsl:param name="var133_current"/>
		<xsl:for-each select="$var133_current/ns0:endpoint">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var132_create_listitem">
				<xsl:with-param name="var131_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var136_create_url">
		<xsl:param name="var135_current"/>
		<url>
			<xsl:value-of select="string($var135_current)"/>
		</url>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var138_create_isAvailable">
		<xsl:param name="var137_current"/>
		<isAvailable>
			<xsl:value-of select="string($var137_current)"/>
		</isAvailable>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var140_create_comment">
		<xsl:param name="var139_current"/>
		<comment>
			<xsl:value-of select="string($var139_current)"/>
		</comment>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var142_create_listitem">
		<xsl:param name="var141_current"/>
		<list-item>
			<xsl:for-each select="$var141_current/ns0:url">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var136_create_url">
					<xsl:with-param name="var135_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var141_current/ns0:isAvailable">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var138_create_isAvailable">
					<xsl:with-param name="var137_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<type>
				<xsl:value-of select="string($var141_current/ns0:type)"/>
			</type>
			<xsl:for-each select="$var141_current/ns0:comment">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var140_create_comment">
					<xsl:with-param name="var139_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var144_create_url">
		<xsl:param name="var143_current"/>
		<url>
			<xsl:value-of select="string($var143_current)"/>
		</url>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var146_create_isAvailable">
		<xsl:param name="var145_current"/>
		<isAvailable>
			<xsl:value-of select="string($var145_current)"/>
		</isAvailable>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var148_create_comment">
		<xsl:param name="var147_current"/>
		<comment>
			<xsl:value-of select="string($var147_current)"/>
		</comment>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var150_create_diskFormat">
		<xsl:param name="var149_current"/>
		<diskFormat>
			<xsl:value-of select="string($var149_current)"/>
		</diskFormat>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var152_create_containerFormat">
		<xsl:param name="var151_current"/>
		<containerFormat>
			<xsl:value-of select="string($var151_current)"/>
		</containerFormat>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var154_create_cmd">
		<xsl:param name="var153_current"/>
		<cmd>
			<xsl:value-of select="string($var153_current)"/>
		</cmd>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var156_create_version">
		<xsl:param name="var155_current"/>
		<version>
			<xsl:value-of select="string($var155_current)"/>
		</version>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var158_create_listitem">
		<xsl:param name="var157_current"/>
		<list-item>
			<xsl:for-each select="$var157_current/ns0:url">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var144_create_url">
					<xsl:with-param name="var143_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var157_current/ns0:isAvailable">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var146_create_isAvailable">
					<xsl:with-param name="var145_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<type>
				<xsl:value-of select="string($var157_current/ns0:type)"/>
			</type>
			<xsl:for-each select="$var157_current/ns0:comment">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var148_create_comment">
					<xsl:with-param name="var147_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var157_current/ns0:diskFormat">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var150_create_diskFormat">
					<xsl:with-param name="var149_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var157_current/ns0:containerFormat">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var152_create_containerFormat">
					<xsl:with-param name="var151_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var157_current/ns0:cmd">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var154_create_cmd">
					<xsl:with-param name="var153_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var157_current/ns0:version">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var156_create_version">
					<xsl:with-param name="var155_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var160_create_url">
		<xsl:param name="var159_current"/>
		<url>
			<xsl:value-of select="string($var159_current)"/>
		</url>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var162_create_isAvailable">
		<xsl:param name="var161_current"/>
		<isAvailable>
			<xsl:value-of select="string($var161_current)"/>
		</isAvailable>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var164_create_comment">
		<xsl:param name="var163_current"/>
		<comment>
			<xsl:value-of select="string($var163_current)"/>
		</comment>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var166_create_listitem">
		<xsl:param name="var165_current"/>
		<list-item>
			<xsl:for-each select="$var165_current/ns0:url">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var160_create_url">
					<xsl:with-param name="var159_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var165_current/ns0:isAvailable">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var162_create_isAvailable">
					<xsl:with-param name="var161_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<type>
				<xsl:value-of select="string($var165_current/ns0:type)"/>
			</type>
			<xsl:for-each select="$var165_current/ns0:comment">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var164_create_comment">
					<xsl:with-param name="var163_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var168_create_isAvailable">
		<xsl:param name="var167_current"/>
		<isAvailable>
			<xsl:value-of select="string($var167_current)"/>
		</isAvailable>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var170_create_doi">
		<xsl:param name="var169_current"/>
		<doi>
			<xsl:value-of select="string($var169_current)"/>
		</doi>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var172_create_pmid">
		<xsl:param name="var171_current"/>
		<pmid>
			<xsl:value-of select="string($var171_current)"/>
		</pmid>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var174_create_pmcid">
		<xsl:param name="var173_current"/>
		<pmcid>
			<xsl:value-of select="string($var173_current)"/>
		</pmcid>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var176_create_type">
		<xsl:param name="var175_current"/>
		<type>
			<xsl:value-of select="string($var175_current)"/>
		</type>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var178_create_version">
		<xsl:param name="var177_current"/>
		<version>
			<xsl:value-of select="string($var177_current)"/>
		</version>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var180_create_listitem">
		<xsl:param name="var179_current"/>
		<list-item>
			<xsl:for-each select="$var179_current/ns0:isAvailable">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var168_create_isAvailable">
					<xsl:with-param name="var167_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var179_current/ns0:doi">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var170_create_doi">
					<xsl:with-param name="var169_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var179_current/ns0:pmid">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var172_create_pmid">
					<xsl:with-param name="var171_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var179_current/ns0:pmcid">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var174_create_pmcid">
					<xsl:with-param name="var173_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var179_current/ns0:type">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var176_create_type">
					<xsl:with-param name="var175_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var179_current/ns0:version">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var178_create_version">
					<xsl:with-param name="var177_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var182_create_elixirPlatform">
		<xsl:param name="var181_current"/>
		<elixirPlatform>
			<xsl:value-of select="string($var181_current)"/>
		</elixirPlatform>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var184_create_elixirNode">
		<xsl:param name="var183_current"/>
		<elixirNode>
			<xsl:value-of select="string($var183_current)"/>
		</elixirNode>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var186_create_name">
		<xsl:param name="var185_current"/>
		<name>
			<xsl:value-of select="string($var185_current)"/>
		</name>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var188_create_orcidId">
		<xsl:param name="var187_current"/>
		<orcidId>
			<xsl:value-of select="string($var187_current)"/>
		</orcidId>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var190_create_gridId">
		<xsl:param name="var189_current"/>
		<gridId>
			<xsl:value-of select="string($var189_current)"/>
		</gridId>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var192_create_email">
		<xsl:param name="var191_current"/>
		<email>
			<xsl:value-of select="string($var191_current)"/>
		</email>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var194_create_url">
		<xsl:param name="var193_current"/>
		<url>
			<xsl:value-of select="string($var193_current)"/>
		</url>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var196_create_tel">
		<xsl:param name="var195_current"/>
		<tel>
			<xsl:value-of select="string($var195_current)"/>
		</tel>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var198_create_typeEntity">
		<xsl:param name="var197_current"/>
		<typeEntity>
			<xsl:value-of select="string($var197_current)"/>
		</typeEntity>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var200_create_typeRole">
		<xsl:param name="var199_current"/>
		<typeRole>
			<xsl:value-of select="string($var199_current)"/>
		</typeRole>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var202_create_comment">
		<xsl:param name="var201_current"/>
		<comment>
			<xsl:value-of select="string($var201_current)"/>
		</comment>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var204_create_listitem">
		<xsl:param name="var203_current"/>
		<list-item>
			<xsl:for-each select="$var203_current/ns0:elixirPlatform">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var182_create_elixirPlatform">
					<xsl:with-param name="var181_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var203_current/ns0:elixirNode">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var184_create_elixirNode">
					<xsl:with-param name="var183_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var203_current/ns0:name">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var186_create_name">
					<xsl:with-param name="var185_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var203_current/ns0:orcidid">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var188_create_orcidId">
					<xsl:with-param name="var187_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var203_current/ns0:gridid">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var190_create_gridId">
					<xsl:with-param name="var189_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var203_current/ns0:email">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var192_create_email">
					<xsl:with-param name="var191_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var203_current/ns0:url">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var194_create_url">
					<xsl:with-param name="var193_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var203_current/ns0:tel">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var196_create_tel">
					<xsl:with-param name="var195_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var203_current/ns0:typeEntity">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var198_create_typeEntity">
					<xsl:with-param name="var197_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var203_current/ns0:typeRole">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var200_create_typeRole">
					<xsl:with-param name="var199_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var203_current/ns0:comment">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var202_create_comment">
					<xsl:with-param name="var201_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</list-item>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var206_create_lastReviewExternalSab">
		<xsl:param name="var205_current"/>
		<lastReviewExternalSab>
			<xsl:value-of select="string($var205_current/ns0:lastReviewExternalSab)"/>
		</lastReviewExternalSab>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var208_create_lastReviewElixirSab">
		<xsl:param name="var207_current"/>
		<lastReviewElixirSab>
			<xsl:value-of select="string($var207_current/ns0:lastReviewElixirSab)"/>
		</lastReviewElixirSab>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var210_create_inSDP">
		<xsl:param name="var209_current"/>
		<inSDP>
			<xsl:value-of select="string((translate(string($var209_current/ns0:inSDP), '1falseru0 ', 't') = 't'))"/>
		</inSDP>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var212_create_isCoreDataResource">
		<xsl:param name="var211_current"/>
		<isCoreDataResource>
			<xsl:value-of select="string((translate(string($var211_current/ns0:isCoreDataResource), '1falseru0 ', 't') = 't'))"/>
		</isCoreDataResource>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var214_create_comment">
		<xsl:param name="var213_current"/>
		<comment>
			<xsl:value-of select="string($var213_current)"/>
		</comment>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var216_resultof_map">
		<xsl:param name="var215_current"/>
		<xsl:for-each select="$var215_current/ns0:comment">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var214_create_comment">
				<xsl:with-param name="var213_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var218_create_root">
		<xsl:param name="var217_current"/>
		<root>
			<name>
				<xsl:value-of select="string($var217_current/ns0:summary/ns0:name)"/>
			</name>
			<xsl:for-each select="$var217_current/ns0:summary/ns0:shortDescription">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var2_create_shortDescription">
					<xsl:with-param name="var1_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<description>
				<xsl:value-of select="string($var217_current/ns0:summary/ns0:description)"/>
			</description>
			<homepage>
				<xsl:value-of select="string($var217_current/ns0:summary/ns0:homepage)"/>
			</homepage>
			<xsl:for-each select="$var217_current/ns0:summary/ns0:biotoolsID">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var4_create_biotoolsID">
					<xsl:with-param name="var3_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var217_current/ns0:summary/ns0:biotoolsCURIE">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var6_create_biotoolsCURIE">
					<xsl:with-param name="var5_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<version>
				<xsl:for-each select="$var217_current/ns0:summary/ns0:version">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var8_create_listitem">
						<xsl:with-param name="var7_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</version>
			<otherID>
				<xsl:for-each select="$var217_current/ns0:summary/ns0:otherID">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var14_create_listitem">
						<xsl:with-param name="var13_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</otherID>
			<function>
				<xsl:for-each select="$var217_current/ns0:function">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var50_create_listitem">
						<xsl:with-param name="var49_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</function>
			<toolType>
				<xsl:for-each select="$var217_current/ns0:labels">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var54_resultof_map">
						<xsl:with-param name="var53_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</toolType>
			<topic>
				<xsl:for-each select="$var217_current/ns0:labels">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var62_resultof_map">
						<xsl:with-param name="var61_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</topic>
			<goTermID>
				<xsl:for-each select="$var217_current/ns0:labels">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var66_resultof_map">
						<xsl:with-param name="var65_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</goTermID>
			<soTermID>
				<xsl:for-each select="$var217_current/ns0:labels">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var70_resultof_map">
						<xsl:with-param name="var69_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</soTermID>
			<taxID>
				<xsl:for-each select="$var217_current/ns0:labels">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var74_resultof_map">
						<xsl:with-param name="var73_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</taxID>
			<operatingSystem>
				<xsl:for-each select="$var217_current/ns0:labels">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var78_resultof_map">
						<xsl:with-param name="var77_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</operatingSystem>
			<language>
				<xsl:for-each select="$var217_current/ns0:labels">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var82_resultof_map">
						<xsl:with-param name="var81_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</language>
			<xsl:for-each select="$var217_current/ns0:labels">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var86_resultof_map">
					<xsl:with-param name="var85_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<collectionID>
				<xsl:for-each select="$var217_current/ns0:labels">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var90_resultof_map">
						<xsl:with-param name="var89_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</collectionID>
			<xsl:for-each select="$var217_current/ns0:labels">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var94_resultof_map">
					<xsl:with-param name="var93_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="$var217_current/ns0:labels">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var98_resultof_map">
					<xsl:with-param name="var97_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<accessibility>
				<xsl:for-each select="$var217_current/ns0:labels">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var102_resultof_map">
						<xsl:with-param name="var101_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</accessibility>
			<relation>
				<xsl:for-each select="$var217_current/ns0:relation">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var104_create_listitem">
						<xsl:with-param name="var103_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</relation>
			<apiSpec>
				<xsl:for-each select="$var217_current/ns0:apiSpec">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var106_create_baseURL">
						<xsl:with-param name="var105_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
				<endpoint>
					<xsl:for-each select="$var217_current/ns0:apiSpec">
						<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var134_resultof_map">
							<xsl:with-param name="var133_current" select="."/>
						</xsl:call-template>
					</xsl:for-each>
				</endpoint>
			</apiSpec>
			<link>
				<xsl:for-each select="$var217_current/ns0:link">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var142_create_listitem">
						<xsl:with-param name="var141_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</link>
			<download>
				<xsl:for-each select="$var217_current/ns0:download">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var158_create_listitem">
						<xsl:with-param name="var157_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</download>
			<documentation>
				<xsl:for-each select="$var217_current/ns0:documentation">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var166_create_listitem">
						<xsl:with-param name="var165_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</documentation>
			<publication>
				<xsl:for-each select="$var217_current/ns0:publication">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var180_create_listitem">
						<xsl:with-param name="var179_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</publication>
			<credit>
				<xsl:for-each select="$var217_current/ns0:credit">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var204_create_listitem">
						<xsl:with-param name="var203_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</credit>
			<elixirInfo>
				<xsl:for-each select="$var217_current/ns0:elixirInfo">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var206_create_lastReviewExternalSab">
						<xsl:with-param name="var205_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
				<xsl:for-each select="$var217_current/ns0:elixirInfo">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var208_create_lastReviewElixirSab">
						<xsl:with-param name="var207_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
				<xsl:for-each select="$var217_current/ns0:elixirInfo">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var210_create_inSDP">
						<xsl:with-param name="var209_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
				<xsl:for-each select="$var217_current/ns0:elixirInfo">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var212_create_isCoreDataResource">
						<xsl:with-param name="var211_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
				<xsl:for-each select="$var217_current/ns0:elixirInfo">
					<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var216_resultof_map">
						<xsl:with-param name="var215_current" select="."/>
					</xsl:call-template>
				</xsl:for-each>
			</elixirInfo>
		</root>
	</xsl:template>
	<xsl:template name="agt:MapTobiotools-3_0_0_framework_var220_resultof_map">
		<xsl:param name="var219_current"/>
		<xsl:for-each select="$var219_current/ns0:tool">
			<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var218_create_root">
				<xsl:with-param name="var217_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template match="/">
		<tools>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">D:/repos/GitHub/biotoolsShim/xml2genericxml/versions/biotools-3.0.0/biotools-3.0.0_framework.xsd</xsl:attribute>
			<xsl:for-each select="ns0:tools">
				<xsl:call-template name="agt:MapTobiotools-3_0_0_framework_var220_resultof_map">
					<xsl:with-param name="var219_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</tools>
	</xsl:template>
</xsl:stylesheet>
